### ISSUE TITLE
Preferred order of fields in the schema

### ISSUE THREAD

**Issue by YeastCell** [CancerDataAggregator/transform#78]
I have compared the schema that I used for practice tables and the one that is currently in use in the integration branch (`gdc-bq-sample.integration.all_v1` table). There are some discrepancies that I found and that I'll list here. Most of these are due to extension of the current data model, but there are some that I would like to double check with both @kreinold and @druth314.

First, to share the schema I used for the practice tables --> https://drive.google.com/drive/u/1/folders/1IwkeQoBhO_Pcygb415nzfSgyj4Q78Gdz

Some further notes and questions:

1. The schema contains my personal preferred order of fields that would make data browsing a bit easier when queried through the `cda-python`. It doesn't contain the **Study** entity since I didn't use this one in practice tables and I'm not sure about the purpose of some fields (see further points down below).
2. Can you confirm that the renaming of `Treatment.type` and `Treatment.outcome` was desired? We now have `Treatment.treatment_type` and `Treatment.treatment_outcome`?
3. Also related to Treatment entity – `days_to_treatment_start` field looks like a INTEGER type rather than STRING.
4. There are multiple entities that contain `associated_project` field – **ResearchSubject**, **Specimen** and **File**. While the former two expect type STRING for the `associated_project` field, the **File** entity defines a list of strings. This to me doesn't make any sense and we should perhaps try to make this consistent across entities. Please comment here if you think otherwise.
5.  On to the **Study** questions – First and foremost – Did we all agree about the Study fields and is this aligned with CCDH recommendations to any extent? The next two points is where I have concerns.
6. The **Study** entity contains two fields that are also present in its parent **ResearchSubject** entity – `primary_disease_site` and `primary_disease_type`. Is this intended design? One **ResearchSubject** item can have more than one **Study** item leading to a potential conflict when working with those fields. Unless all studies belonging to the same **ResearchSubject** entry will have a single value for these fields.
7. There is also`pdc_study_id` field within the **Study** entity. **Introducing node-specific fields into our data model/representation is pretty dangerous and it is something we should avoid if at all possible** (attn @kreinold @DavidPotCanuck). In this particular case it looks like we are adding yet another study identifier, but it is PDC-specific. Does anyone know why this information needs its own field? I remember that we encountered a similar issue with `gdc_sample_id` field back when we worked on R1, but we figured that this information is used as a linker and found another way to link specimens. If the `pdc_study_id` is also some kind of linker, I suggest considering placing it into **identifier** entity.

**Comment by druth314** [comment]
@YeastCell thank you for the updated preference in field order. I'll arrange the mapping files to reflect those issues. 
1) The current schema includes a Study entity which I intend to remove in the next update to the tables. Last I was aware, the main folks that used Study info from PDC are not going to be needing it anymore.
2) This was an item that @kreinold had brought up before. This change matches what is in the CCDH model, as well as the JSON schema files that are in the cda-data-model branch
3) I believe you are correct and this may be a typo in the cda-data-model branch for the Treatment entity. @kreinold can you confirm or edit the relevant file?
4) This is an inconsistency that should be fixed. As far as I know, the associated_project field (no matter what entity it is in) is meant to be a list, since it references links to potentially multiple projects. We do not do aggregating of projects for the ResearchSubject, Specimen, or File entities at this time though, so I will make it simply a string.
5, 6, 7) I am removing Study entity so this can be discussed later. Thank you for catching all of these inconsistencies.

**Comment by druth314** [comment]
@YeastCell I was looking over your preferred order and was hoping to clarify a few things:
1) In the Patient entity we were planning on adding species, and subject_associated_project. Could you please add them to the JSON as you see fit?
2) I recall you stating that you did not prefer having the Patient level File information listed before the ResearchSubject entity. I am probably mistaken but I wanted to verify it before altering the transformation code.
3) In the File entity, where would you prefer data_modality and imaging_modality fields? Could you please add them to the JSON as you see fit?
4) In the Treatment entity, we also have days_to_treatment_end. I assume you would prefer it just after days_to_treatment_start, but let me know just to be sure. 

Overall I like the new order of this JSON schema. It's a good arrangement for searching the fields in our tables.

**Comment by kreinold** [comment]
1. - fyi, subject_associated_project should look just like associated_project.  Just need to capture it at the Subject level because IDC doesn't have ResearchSubject.
2. no comment from me
3. Yes, it should be integer 
4. Interesting question.  
- Specimen
--   CRDC-H only allows 1; this makes sense at the aliquot level but there could be a use case where CDA users will expect to select a sample and ask for all projects that used that sample.
--   In CDA we could select all child specimens to the aliquot level and return the list of projects or we could store that data.  Seems like calculating it is the right answer because it’s a value that could change.
- ResearchSubject
--   Given the definition of ResearchSubject, it is the project-specific info about a Subject in a Project, there should be only 1 but CRDC-H allows multiple projects for a ResearchSubject.
- File
--  File should be reporting the Project that created the File, thus, I'd expect only 1.  CRDC-H doesn't include File yet so it’s our call.

Agree w/ removing study and avoiding 5-7.

**Comment by YeastCell** [comment]
@druth314 I have finally uploaded an updated schema (same file: `r2_schema_wo_study.json`).
Here is what has changed:

- **Patient** entity got new fields/entities: `identifier`, `species`, `associated_project`.
- **Treatment** entity got `days_to_treatment_end` field.
- The order of certain fields has been further adjusted.

Comments:

1. Confirming that the **File** entity before **ResearchSubject** entity is the preferred order. My logic for this was to push the **File** entity towards the end of the corresponding list, but not after those entities that also contain **File** entity.
2. Based on your comment @druth314 about the fact that we don't aggregate projects and based on Kathy's clarification, I agree that we should keep `associated_project` field as a single STRING value (reflected in the updated schema). Maybe the list would make more sense at some point in the future, but for now there is no point of keeping it as a list since it will always contain a single value in the current implementation set-up.
3.  I didn't go on to add `data_modality` and `imaging_modality` to the File entity, since I feel like we need further discussions about those fields. Hence, I'd ask if we could ignore those fields temporarily. My main concern is that some of that information would look repetitive. @kreinold can we add this to our data model breakout session agenda? I'm sure that you have more insights about this.
4. I have added the `days_to_treatment_end` field to the schema as well. @druth314 I saw that this one was also of type STRING in your `upload_test` table – please, let me know if I can help you verify the schema in the next iteration and make sure everything is as expected.

**Comment by fkaufman-asym** [comment]
Done, tested and Merged
